# Generated by Django 4.2.7 on 2023-11-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
