# Generated by Django 4.2.7 on 2023-11-28 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.person'),
        ),
    ]
