# Generated by Django 5.0 on 2023-12-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_inventory_is_active_remove_location_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
