# Generated by Django 5.0 on 2023-12-14 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_itemquantity_statement_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemquantity',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('storestatement', 'locationstatement')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
