# Generated by Django 4.2.7 on 2024-01-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_itemquantity_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='pend',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
